---
- name: install rbenv
  sudo: true
  git: repo=https://github.com/sstephenson/rbenv.git
       dest={{ vagrant_home }}/.rbenv
       version=master

- name: install ruby_build
  sudo: true
  git: repo=https://github.com/sstephenson/ruby-build.git
       dest={{ vagrant_home }}/.rbenv/plugins/ruby-build
       version=master

- name: Add ~.rbenv/bin to PATH
  lineinfile:
    dest: "~/.bashrc"
    line: "export PATH=$HOME/.rbenv/bin:$PATH"

- name: Eval rbenv init in ~/.profile
  lineinfile:
    dest: "~/.bashrc"
    line: 'eval "$(rbenv init -)"'

- name: install ruby 2.2.3
  sudo: true
  shell: "export RBENV_ROOT={{ vagrant_home }}/.rbenv;
          export PATH=$RBENV_ROOT/bin:$PATH;
          echo N | rbenv install {{ ruby_version }};
          rbenv global {{ ruby_version }}"
  args:
    creates: "{{ vagrant_home }}/.rbenv/versions/{{ ruby_version }}/"

- name: install bundler
  sudo: true
  shell: "{{ vagrant_home }}/.rbenv/shims/gem install bundler"
  args:
    creates: "{{ vagrant_home }}/.rbenv/shims/bundle"

- name: bundler install
  gem:
    name: bundler
    executable: /home/vagrant/.rbenv/shims/gem
    user_install: false
